### ISSUE TITLE
PendingIntents attached to actions with remote inputs must be mutable

### ISSUE THREAD

**Issue by dieehard** [qiscus/qiscus-sdk-android#101]
Qiscus Chat SDK (buildIn) 2.31.3

App crashed when chat notification arrived. 

Error: PendingIntents attached to actions with remote inputs must be mutable

Stacktrace:
  at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:223)
  at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:205)
  at com.qiscus.sdk.util.QiscusPushNotificationUtil.lambda$pushNotification$6(QiscusPushNotificationUtil.java:344)
  at com.qiscus.sdk.util.-$$Lambda$QiscusPushNotificationUtil$uk81Wpi_y-UBE25yWqUnDqr9M24.run(Unknown Source:6)

Please update the buildin sdk to latest version of chat-core.

**Comment by ariefnurputranto** [comment]
Thanks for report sir @dieehard , 

We haven't maintained SDK Chat BuildIn UI for a long time, and the company itself suggests migrating to SDK Chat Core for better future development.

Please migration from Qiscus Chat SDK (BuildIn) to Qiscus Chat SDK (Core), 

link sample, https://github.com/qiscus/qiscus-chat-sdk-android-sample
link docs , https://documentation.qiscus.com/chat-sdk-android
