### ISSUE TITLE
java.lang.NoClassDefFoundError: com.vanniktech.emoji.one.EmojiOneProvider Against Android API 19 (4.4.2)

### ISSUE THREAD

**Issue by EdwardQuixote** [qiscus/qiscus-sdk-android#16]
I encountered the following error as I tested version `2.8.0` against Android API 19 - 4.4.2. (`com.qiscus.sdk:chat:2.8.0`)

This error occurs at line:
`Qiscus.init(this, "MY_APP_ID");`

Error Log:
`FATAL EXCEPTION: main
                                                                                Process: com.smartapplications.smartapp, PID: 27042
                                                                                java.lang.NoClassDefFoundError: com.vanniktech.emoji.one.EmojiOneProvider
                                                                                    at com.qiscus.sdk.Qiscus.initWithCustomServer(Qiscus.java:138)
                                                                                    at com.qiscus.sdk.Qiscus.init(Qiscus.java:98)
                                                                                    at com.smartapplications.smartapp.SmartApp.onCreate(SmartApp.java:37)
                                                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4582)
                                                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                    at android.os.Looper.loop(Looper.java:193)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                                    at dalvik.system.NativeStart.main(Native Method)`

**Comment by zetbaitsu** [comment]
Can you elaborate how you got that error? why before it you didn't get that error?

or try to put emoji provider dependencies to your gradle file:
```
compile 'com.vanniktech:emoji-one:0.5.0'
```

*sorry for my bad english

**Comment by EdwardQuixote** [comment]
@zetbaitsu I hadn't tested my App in any Android API 19 device before. This was the first time.
I have `Qiscus.init(this, "MY_APP_ID");` in my Application class.
The logs are above. I literally can't explain why I got this error. Please take note the Device I'm using is:
HTC 820 G+ Dual-sim running stock (unmodified) Android OS API 19 (4.4.2)

@zetbaitsu even with this separate dependency: `compile 'com.vanniktech:emoji-one:0.5.0'`, the App still fails with the same error.

**Comment by zetbaitsu** [comment]
is the error happened to debug version too? or only when you activated proguard or signed APKs?

**Comment by andhicapratama** [comment]
I also has the same issue .. I don't know when that errors occur... or I don't know if I erase something. but as I remember, I don't change anything about the emoticon. How to fix it?

**Comment by rajapulau** [comment]
hi @andhicapratama 

which version you use our sdk ? we recommend you use our qiscus chat sdk core https://github.com/qiscus/qiscus-chat-sdk-android-sample

Documentation:
https://docs.qiscus.com/android/latest/introduction#getting-started

you can freely to implement your own emoji

**Comment by andhicapratama** [comment]
i use 
implementation('com.qiscus.sdk:chat:2.28.1') {
        exclude group: 'com.google.android.gms'
    }

**Comment by andhicapratama** [comment]
but when I run with another laptop, it runs without any error.. what its like that?
