### ISSUE TITLE
Support for Glide 4

### ISSUE THREAD

**Issue by mahasadhu** [qiscus/qiscus-sdk-android#17]
I got this error every time qiscus try to show a notification. It seems like caused by the Glide ver. 4 that I'm using, since the new Glide library has a slightly different way to call their methods.

> FATAL EXCEPTION: main
                                                                     Process: com.dokterchat.expert, PID: 3736
                                                                     java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.xxx.xxx-1/base.apk:classes55.dex)
                                                                         at com.qiscus.sdk.util.QiscusPushNotificationUtil.loadAvatar(QiscusPushNotificationUtil.java:117)
                                                                         at com.qiscus.sdk.util.QiscusPushNotificationUtil.lambda$showPushNotification$1(QiscusPushNotificationUtil.java:108)
                                                                         at com.qiscus.sdk.util.QiscusPushNotificationUtil$$Lambda$2.run(Unknown Source)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by zetbaitsu** [comment]
We are sorry for compatibility issues with current apps, we are decide still to using glide 3.8.0.. you can use 3.8.0 version too.

We will support Glide version 4 at Qiscus SDK 3.0.0.. thanks for the feedback.

**Comment by mahasadhu** [comment]
Ah okay I got it. Thanks.
